version: '3.1'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "3306:3306"
    volumes:
      - ./db/seed:/docker-entrypoint-initdb.d
  web:
    build: .
    image: myphp
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
networks:
  default:
    external:
      name: slimApi

# vim: set expandtab tabstop=2
