version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  web:
    image: wordpress:4.8.3-php7.0-apache
    ports:
      - "8000:80"
    volumes:
      - ./files:/var/www/html
    depends_on:
      - db
networks:
  default:
    external:
      name: jimmy

# vim: set expandtab tabstop=2:
