#!/bin/python
import requests


def get_wifi():
    try:
        r = requests.get('http://api.wunderground.com/api/d0504b212b9495e7/'
                         'conditions/q/us/mi/allendale.json')
    except TimeoutError:
        print('No WiFi playa')
        return

    info = r.json()
    weather = info["current_observation"]["weather"]
    temp = info["current_observation"]["temp_f"]

    print(weather, str(temp) + "°F")


get_wifi()
